package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// PhotoSpec defines the desired state of Photo
type PhotoSpec struct {
	// Name is the display name of the photo
	Name string `json:"name,omitempty"`

	// Description provides additional information about the photo
	Description string `json:"description,omitempty"`

	// URL is the location where the photo can be accessed
	URL string `json:"url,omitempty"`

	// Score represents a rating or quality score for the photo
	Score int `json:"score,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *PhotoSpec) DeepCopyInto(out *PhotoSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhotoSpec.
func (in *PhotoSpec) DeepCopy() *PhotoSpec {
	if in == nil {
		return nil
	}
	out := new(PhotoSpec)
	in.DeepCopyInto(out)
	return out
}

// PhotoStatus defines the observed state of Photo
type PhotoStatus struct {
	// LastUpdated shows when the photo was last processed
	LastUpdated metav1.Time `json:"lastUpdated,omitempty"`

	// ProcessingStatus indicates the current processing state
	ProcessingStatus string `json:"processingStatus,omitempty"`

	// Message provides additional information about the current state
	Message string `json:"message,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *PhotoStatus) DeepCopyInto(out *PhotoStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhotoStatus.
func (in *PhotoStatus) DeepCopy() *PhotoStatus {
	if in == nil {
		return nil
	}
	out := new(PhotoStatus)
	in.DeepCopyInto(out)
	return out
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:printcolumn:name="Name",type=string,JSONPath=`.spec.name`
//+kubebuilder:printcolumn:name="Description",type=string,JSONPath=`.spec.description`
//+kubebuilder:printcolumn:name="URL",type=string,JSONPath=`.spec.url`
//+kubebuilder:printcolumn:name="Score",type=integer,JSONPath=`.spec.score`
//+kubebuilder:printcolumn:name="Status",type=string,JSONPath=`.status.processingStatus`

// Photo is the Schema for the photos API
type Photo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PhotoSpec   `json:"spec,omitempty"`
	Status PhotoStatus `json:"status,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *Photo) DeepCopyInto(out *Photo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Photo.
func (in *Photo) DeepCopy() *Photo {
	if in == nil {
		return nil
	}
	out := new(Photo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Photo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

//+kubebuilder:object:root=true

// PhotoList contains a list of Photo
type PhotoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Photo `json:"items"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *PhotoList) DeepCopyInto(out *PhotoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Photo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhotoList.
func (in *PhotoList) DeepCopy() *PhotoList {
	if in == nil {
		return nil
	}
	out := new(PhotoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhotoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
